spring:
  application:
    name: taskHub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taskhub?useTimezone=true&serverTimezone=UTC
    username: developer
    password: 1234567
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false
  mail:
    host: smtp.google.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
mail:
  from:
    name: Jo√£o Junio
security:
  jwt:
    token:
      secret-key: 57cr37
      expire-length: 3600000
web-push:
  vapid:
    public-key: BGkzHGbnUqBqE_2abbp0HDsFdzMdBmfA-mc7LZtKm156oXwDu8TK5Zs1BLptLpkA5D9kEjynH6K6iKPkqRWN40c
    private-key: hNtIQfBu4lt5rFadP3wPKNQkqHV9Bf7W2e8xD-55tUo
    subject: jotacastrotrd@gmail.com